// Master data: real pincodes/areas for all Tamil Nadu districts
// Used by auto-generate endpoint to bulk-create areas

module.exports = {
  "Ariyalur": [
    { pincode: "621701", area: "Ariyalur", city: "Ariyalur" },
    { pincode: "621702", area: "T.Palur", city: "Ariyalur" },
    { pincode: "621703", area: "Sendurai", city: "Sendurai" },
    { pincode: "621704", area: "Udayarpalayam", city: "Udayarpalayam" },
    { pincode: "621705", area: "Andimadam", city: "Andimadam" },
    { pincode: "621706", area: "Jayankondam", city: "Jayankondam" },
    { pincode: "621707", area: "Thirumanur", city: "Thirumanur" },
    { pincode: "621708", area: "Ponparappi", city: "Ariyalur" },
    { pincode: "621709", area: "Reddipalayam", city: "Ariyalur" },
    { pincode: "621710", area: "Kallankurichi", city: "Ariyalur" },
    { pincode: "621711", area: "Gangavalli", city: "Ariyalur" },
    { pincode: "621712", area: "Varadarajanpettai", city: "Ariyalur" },
    { pincode: "621713", area: "Vilangudi", city: "Ariyalur" },
    { pincode: "612602", area: "Lalgudi (part)", city: "Ariyalur" },
  ],

  "Chengalpattu": [
    { pincode: "603001", area: "Chengalpattu", city: "Chengalpattu" },
    { pincode: "603002", area: "Chengalpattu Bazaar", city: "Chengalpattu" },
    { pincode: "603003", area: "Singaperumal Koil", city: "Chengalpattu" },
    { pincode: "603101", area: "Mahabalipuram", city: "Mahabalipuram" },
    { pincode: "603102", area: "Thiruporur", city: "Thiruporur" },
    { pincode: "603103", area: "Kelambakkam", city: "Kelambakkam" },
    { pincode: "603104", area: "Padur", city: "Chengalpattu" },
    { pincode: "603110", area: "Tambaram", city: "Tambaram" },
    { pincode: "603202", area: "Maduranthakam", city: "Maduranthakam" },
    { pincode: "603203", area: "Karunguzhi", city: "Chengalpattu" },
    { pincode: "603204", area: "Cheyyur", city: "Cheyyur" },
    { pincode: "603210", area: "Tirukalukundram", city: "Tirukalukundram" },
    { pincode: "603211", area: "Vandalur", city: "Vandalur" },
    { pincode: "603301", area: "Acharapakkam", city: "Chengalpattu" },
    { pincode: "603302", area: "Chithamur", city: "Chengalpattu" },
    { pincode: "603303", area: "Lathur", city: "Chengalpattu" },
    { pincode: "603401", area: "Maraimalai Nagar", city: "Maraimalai Nagar" },
    { pincode: "600048", area: "Pallavaram", city: "Pallavaram" },
    { pincode: "600044", area: "Chromepet", city: "Chromepet" },
    { pincode: "600045", area: "Tambaram East", city: "Tambaram" },
    { pincode: "600059", area: "Tambaram West", city: "Tambaram" },
    { pincode: "600073", area: "Guduvanchery", city: "Guduvanchery" },
    { pincode: "600119", area: "Perungalathur", city: "Perungalathur" },
    { pincode: "600130", area: "Urapakkam", city: "Urapakkam" },
  ],

  "Chennai": [
    { pincode: "600001", area: "George Town", city: "Chennai" },
    { pincode: "600002", area: "Washer Manpet", city: "Chennai" },
    { pincode: "600003", area: "Park Town", city: "Chennai" },
    { pincode: "600004", area: "Royapettah", city: "Chennai" },
    { pincode: "600005", area: "Triplicane", city: "Chennai" },
    { pincode: "600006", area: "Mylapore", city: "Chennai" },
    { pincode: "600007", area: "Chetpet", city: "Chennai" },
    { pincode: "600008", area: "Egmore", city: "Chennai" },
    { pincode: "600009", area: "Saidapet", city: "Chennai" },
    { pincode: "600010", area: "Vepery", city: "Chennai" },
    { pincode: "600011", area: "Perambur", city: "Chennai" },
    { pincode: "600012", area: "Perambur Barracks", city: "Chennai" },
    { pincode: "600013", area: "Purasawalkam", city: "Chennai" },
    { pincode: "600014", area: "Nungambakkam", city: "Chennai" },
    { pincode: "600015", area: "Adyar", city: "Chennai" },
    { pincode: "600016", area: "Santhome", city: "Chennai" },
    { pincode: "600017", area: "T Nagar", city: "Chennai" },
    { pincode: "600018", area: "Alwarpet", city: "Chennai" },
    { pincode: "600019", area: "Guindy", city: "Chennai" },
    { pincode: "600020", area: "Adyar (West)", city: "Chennai" },
    { pincode: "600021", area: "Washermanpet", city: "Chennai" },
    { pincode: "600022", area: "Royapuram", city: "Chennai" },
    { pincode: "600023", area: "Tondiarpet", city: "Chennai" },
    { pincode: "600024", area: "Kodambakkam", city: "Chennai" },
    { pincode: "600025", area: "Anna Road", city: "Chennai" },
    { pincode: "600026", area: "Kilpauk", city: "Chennai" },
    { pincode: "600027", area: "Anna Salai", city: "Chennai" },
    { pincode: "600028", area: "Teynampet", city: "Chennai" },
    { pincode: "600029", area: "Kotturpuram", city: "Chennai" },
    { pincode: "600030", area: "Velachery", city: "Chennai" },
    { pincode: "600031", area: "Kellys", city: "Chennai" },
    { pincode: "600032", area: "Ashok Nagar", city: "Chennai" },
    { pincode: "600033", area: "West Mambalam", city: "Chennai" },
    { pincode: "600034", area: "Nandanam", city: "Chennai" },
    { pincode: "600035", area: "Thousand Lights", city: "Chennai" },
    { pincode: "600036", area: "Raj Bhavan", city: "Chennai" },
    { pincode: "600037", area: "Besant Nagar", city: "Chennai" },
    { pincode: "600038", area: "Thiruvanmiyur", city: "Chennai" },
    { pincode: "600039", area: "Sholinganallur", city: "Chennai" },
    { pincode: "600040", area: "Alandur", city: "Chennai" },
    { pincode: "600041", area: "Virugambakkam", city: "Chennai" },
    { pincode: "600042", area: "Porur", city: "Chennai" },
    { pincode: "600043", area: "Ramapuram", city: "Chennai" },
    { pincode: "600046", area: "Nanganallur", city: "Chennai" },
    { pincode: "600047", area: "Madipakkam", city: "Chennai" },
    { pincode: "600049", area: "Anna Nagar", city: "Chennai" },
    { pincode: "600050", area: "Anna Nagar West", city: "Chennai" },
    { pincode: "600051", area: "Villivakkam", city: "Chennai" },
    { pincode: "600052", area: "Kolathur", city: "Chennai" },
    { pincode: "600053", area: "Arumbakkam", city: "Chennai" },
    { pincode: "600054", area: "Korattur", city: "Chennai" },
    { pincode: "600055", area: "Mogappair", city: "Chennai" },
    { pincode: "600056", area: "Ambattur", city: "Chennai" },
    { pincode: "600058", area: "Aminjikarai", city: "Chennai" },
    { pincode: "600060", area: "Thirumangalam", city: "Chennai" },
    { pincode: "600061", area: "Madhavaram", city: "Chennai" },
    { pincode: "600062", area: "Red Hills", city: "Chennai" },
    { pincode: "600064", area: "K K Nagar", city: "Chennai" },
    { pincode: "600069", area: "Padi", city: "Chennai" },
    { pincode: "600070", area: "Ennore", city: "Chennai" },
    { pincode: "600078", area: "Avadi", city: "Chennai" },
    { pincode: "600083", area: "Manali", city: "Chennai" },
    { pincode: "600085", area: "Medavakkam", city: "Chennai" },
    { pincode: "600086", area: "Perungudi", city: "Chennai" },
    { pincode: "600089", area: "Thoraipakkam", city: "Chennai" },
    { pincode: "600091", area: "Poonamallee", city: "Chennai" },
    { pincode: "600092", area: "Kunrathur", city: "Chennai" },
    { pincode: "600095", area: "Palavakkam", city: "Chennai" },
    { pincode: "600096", area: "Neelankarai", city: "Chennai" },
    { pincode: "600097", area: "Navalur", city: "Chennai" },
    { pincode: "600100", area: "Taramani", city: "Chennai" },
    { pincode: "600101", area: "Thiruverkadu", city: "Chennai" },
    { pincode: "600107", area: "Iyyappanthangal", city: "Chennai" },
    { pincode: "600113", area: "Mangadu", city: "Chennai" },
    { pincode: "600116", area: "Kattupakkam", city: "Chennai" },
    { pincode: "600117", area: "Mugalivakkam", city: "Chennai" },
    { pincode: "600118", area: "Kovur", city: "Chennai" },
    { pincode: "600125", area: "Nolambur", city: "Chennai" },
    { pincode: "600126", area: "Puzhal", city: "Chennai" },
    { pincode: "600128", area: "Minjur", city: "Chennai" },
  ],

  "Cuddalore": [
    { pincode: "607001", area: "Cuddalore", city: "Cuddalore" },
    { pincode: "607002", area: "Cuddalore Port", city: "Cuddalore" },
    { pincode: "607003", area: "Cuddalore Old Town", city: "Cuddalore" },
    { pincode: "607004", area: "Manjakuppam", city: "Cuddalore" },
    { pincode: "607101", area: "Chidambaram", city: "Chidambaram" },
    { pincode: "607102", area: "Annamalai Nagar", city: "Chidambaram" },
    { pincode: "607103", area: "Parangipettai", city: "Parangipettai" },
    { pincode: "607104", area: "Sethiathope", city: "Chidambaram" },
    { pincode: "607105", area: "Bhuvanagiri", city: "Bhuvanagiri" },
    { pincode: "607106", area: "Kattumannarkoil", city: "Kattumannarkoil" },
    { pincode: "607201", area: "Panruti", city: "Panruti" },
    { pincode: "607202", area: "Nellikuppam", city: "Cuddalore" },
    { pincode: "607203", area: "Virudhachalam", city: "Virudhachalam" },
    { pincode: "607301", area: "Tittagudi", city: "Tittagudi" },
    { pincode: "607302", area: "Kurinjipadi", city: "Kurinjipadi" },
    { pincode: "607303", area: "Vriddhachalam", city: "Vriddhachalam" },
    { pincode: "607401", area: "Melpattampakkam", city: "Cuddalore" },
    { pincode: "607402", area: "Kammapuram", city: "Cuddalore" },
  ],

  "Dharmapuri": [
    { pincode: "636701", area: "Dharmapuri", city: "Dharmapuri" },
    { pincode: "636702", area: "Dharmapuri Collectorate", city: "Dharmapuri" },
    { pincode: "636703", area: "Palacode", city: "Palacode" },
    { pincode: "636704", area: "Pennagaram", city: "Pennagaram" },
    { pincode: "636705", area: "Harur", city: "Harur" },
    { pincode: "636801", area: "Nallampalli", city: "Dharmapuri" },
    { pincode: "636802", area: "Pappireddipatti", city: "Pappireddipatti" },
    { pincode: "636803", area: "Karimangalam", city: "Karimangalam" },
    { pincode: "636804", area: "Morappur", city: "Morappur" },
    { pincode: "636805", area: "Eriyur", city: "Dharmapuri" },
    { pincode: "636806", area: "Marandahalli", city: "Dharmapuri" },
    { pincode: "636807", area: "Bommidi", city: "Dharmapuri" },
    { pincode: "636808", area: "Kadathur", city: "Dharmapuri" },
    { pincode: "636809", area: "Laligam", city: "Dharmapuri" },
  ],

  "Dindigul": [
    { pincode: "624001", area: "Dindigul", city: "Dindigul" },
    { pincode: "624002", area: "Dindigul Fort", city: "Dindigul" },
    { pincode: "624003", area: "Begampur", city: "Dindigul" },
    { pincode: "624004", area: "Dindigul Collectorate", city: "Dindigul" },
    { pincode: "624005", area: "Dindigul East", city: "Dindigul" },
    { pincode: "624101", area: "Palani", city: "Palani" },
    { pincode: "624102", area: "Tharamangalam", city: "Palani" },
    { pincode: "624201", area: "Oddanchatram", city: "Oddanchatram" },
    { pincode: "624202", area: "Natham", city: "Natham" },
    { pincode: "624203", area: "Vedasandur", city: "Vedasandur" },
    { pincode: "624204", area: "Vadamadurai", city: "Dindigul" },
    { pincode: "624301", area: "Batlagundu", city: "Batlagundu" },
    { pincode: "624302", area: "Nilakottai", city: "Nilakottai" },
    { pincode: "624401", area: "Kodaikanal", city: "Kodaikanal" },
    { pincode: "624402", area: "Kodai Road", city: "Kodaikanal" },
    { pincode: "624601", area: "Attur (Dindigul)", city: "Dindigul" },
    { pincode: "624612", area: "Guziliamparai", city: "Dindigul" },
    { pincode: "624615", area: "Reddiarchatram", city: "Dindigul" },
    { pincode: "624619", area: "Sithayankottai", city: "Dindigul" },
  ],

  "Erode": [
    { pincode: "638001", area: "Erode", city: "Erode" },
    { pincode: "638002", area: "Erode Fort", city: "Erode" },
    { pincode: "638003", area: "Erode Collectorate", city: "Erode" },
    { pincode: "638004", area: "Veerappanchatram", city: "Erode" },
    { pincode: "638005", area: "Karungalpalayam", city: "Erode" },
    { pincode: "638007", area: "Surampatti", city: "Erode" },
    { pincode: "638009", area: "Chithode", city: "Erode" },
    { pincode: "638011", area: "Perundurai", city: "Perundurai" },
    { pincode: "638012", area: "Modakkurichi", city: "Erode" },
    { pincode: "638051", area: "Bhavani", city: "Bhavani" },
    { pincode: "638052", area: "Bhavani Sagar", city: "Bhavani" },
    { pincode: "638053", area: "Kodumudi", city: "Kodumudi" },
    { pincode: "638054", area: "Chennimalai", city: "Chennimalai" },
    { pincode: "638101", area: "Gobichettipalayam", city: "Gobichettipalayam" },
    { pincode: "638102", area: "Sathyamangalam", city: "Sathyamangalam" },
    { pincode: "638103", area: "Nambiyur", city: "Erode" },
    { pincode: "638104", area: "Ammapet", city: "Erode" },
    { pincode: "638151", area: "Anthiyur", city: "Anthiyur" },
    { pincode: "638152", area: "Thalavadi", city: "Erode" },
    { pincode: "638153", area: "Bhavanisagar Dam", city: "Erode" },
    { pincode: "638301", area: "Sivagiri (Erode)", city: "Erode" },
    { pincode: "638312", area: "Elathur", city: "Erode" },
    { pincode: "638315", area: "Kavundapadi", city: "Erode" },
  ],

  "Kallakurichi": [
    { pincode: "606202", area: "Kallakurichi", city: "Kallakurichi" },
    { pincode: "606201", area: "Ulundurpet", city: "Ulundurpet" },
    { pincode: "606203", area: "Chinnasalem", city: "Chinnasalem" },
    { pincode: "606204", area: "Sankarapuram", city: "Sankarapuram" },
    { pincode: "606205", area: "Tirukoilur", city: "Tirukoilur" },
    { pincode: "606206", area: "Rishivandiyam", city: "Kallakurichi" },
    { pincode: "606207", area: "Thirunavalur", city: "Kallakurichi" },
    { pincode: "606208", area: "Kalvarayan Hills", city: "Kallakurichi" },
    { pincode: "606209", area: "Manalur", city: "Kallakurichi" },
    { pincode: "606210", area: "Tirukkoyilur", city: "Kallakurichi" },
    { pincode: "606301", area: "Thiyagadurgam", city: "Kallakurichi" },
    { pincode: "606302", area: "Anangur", city: "Kallakurichi" },
  ],

  "Kancheepuram": [
    { pincode: "631501", area: "Kancheepuram", city: "Kancheepuram" },
    { pincode: "631502", area: "Kanchipuram Bazaar", city: "Kancheepuram" },
    { pincode: "631503", area: "Enathur", city: "Kancheepuram" },
    { pincode: "631504", area: "Pillaiyarpalayam", city: "Kancheepuram" },
    { pincode: "631561", area: "Sriperumbudur", city: "Sriperumbudur" },
    { pincode: "631601", area: "Uthiramerur", city: "Uthiramerur" },
    { pincode: "631602", area: "Walajabad", city: "Walajabad" },
    { pincode: "631603", area: "Kundrathur (Kanchi)", city: "Kancheepuram" },
    { pincode: "631604", area: "Oragadam", city: "Kancheepuram" },
    { pincode: "631605", area: "Sunguvarchatram", city: "Sriperumbudur" },
    { pincode: "631606", area: "Kattankulathur", city: "Kancheepuram" },
    { pincode: "602105", area: "Thirumazhisai", city: "Kancheepuram" },
    { pincode: "602108", area: "Tiruvallur Road", city: "Kancheepuram" },
    { pincode: "602117", area: "Manavala Nagar", city: "Sriperumbudur" },
  ],

  "Karur": [
    { pincode: "639001", area: "Karur", city: "Karur" },
    { pincode: "639002", area: "Karur Town", city: "Karur" },
    { pincode: "639003", area: "Karur Paramathi", city: "Karur" },
    { pincode: "639004", area: "Karur Collectorate", city: "Karur" },
    { pincode: "639005", area: "Pugalur", city: "Pugalur" },
    { pincode: "639006", area: "Vangal", city: "Karur" },
    { pincode: "639101", area: "Kulithalai", city: "Kulithalai" },
    { pincode: "639102", area: "Mayanur", city: "Karur" },
    { pincode: "639103", area: "Thogaimalai", city: "Karur" },
    { pincode: "639104", area: "Aravakurichi", city: "Aravakurichi" },
    { pincode: "639105", area: "Krishnarayapuram", city: "Krishnarayapuram" },
    { pincode: "639201", area: "Kadavur", city: "Karur" },
    { pincode: "639202", area: "Thanthoni", city: "Karur" },
    { pincode: "639136", area: "Manmangalam", city: "Karur" },
  ],

  "Krishnagiri": [
    { pincode: "635001", area: "Krishnagiri", city: "Krishnagiri" },
    { pincode: "635002", area: "Krishnagiri Fort", city: "Krishnagiri" },
    { pincode: "635101", area: "Hosur", city: "Hosur" },
    { pincode: "635102", area: "Hosur Industrial Area", city: "Hosur" },
    { pincode: "635103", area: "Shoolagiri", city: "Shoolagiri" },
    { pincode: "635104", area: "Denkanikottai", city: "Denkanikottai" },
    { pincode: "635105", area: "Kelamangalam", city: "Krishnagiri" },
    { pincode: "635106", area: "Rayakottai", city: "Krishnagiri" },
    { pincode: "635107", area: "Anchetty", city: "Krishnagiri" },
    { pincode: "635108", area: "Pochampalli", city: "Pochampalli" },
    { pincode: "635109", area: "Thalli", city: "Thalli" },
    { pincode: "635110", area: "Bargur", city: "Bargur" },
    { pincode: "635111", area: "Mathigiri", city: "Hosur" },
    { pincode: "635112", area: "Kaveripattinam", city: "Kaveripattinam" },
    { pincode: "635113", area: "Veppanapalli", city: "Krishnagiri" },
    { pincode: "635114", area: "Uthangarai", city: "Uthangarai" },
    { pincode: "635115", area: "Natrampalli", city: "Krishnagiri" },
    { pincode: "635120", area: "Sulagiri", city: "Krishnagiri" },
    { pincode: "635121", area: "Hosur (SIPCOT)", city: "Hosur" },
    { pincode: "635122", area: "Urigam", city: "Krishnagiri" },
    { pincode: "635126", area: "Samalpatti", city: "Krishnagiri" },
    { pincode: "635130", area: "Hosur (Nallur)", city: "Hosur" },
  ],

  "Madurai": [
    { pincode: "625001", area: "Madurai GPO", city: "Madurai" },
    { pincode: "625002", area: "Madurai Meenakshi Temple", city: "Madurai" },
    { pincode: "625003", area: "Bibikulam", city: "Madurai" },
    { pincode: "625004", area: "Jaihindpuram", city: "Madurai" },
    { pincode: "625005", area: "KK Nagar (Madurai)", city: "Madurai" },
    { pincode: "625006", area: "Tallakulam", city: "Madurai" },
    { pincode: "625007", area: "Sellur", city: "Madurai" },
    { pincode: "625009", area: "Madurai Collectorate", city: "Madurai" },
    { pincode: "625010", area: "Narimedu", city: "Madurai" },
    { pincode: "625011", area: "Thiruparankundram", city: "Madurai" },
    { pincode: "625012", area: "Vilangudi (Madurai)", city: "Madurai" },
    { pincode: "625014", area: "Anna Nagar (Madurai)", city: "Madurai" },
    { pincode: "625016", area: "Simmakkal", city: "Madurai" },
    { pincode: "625017", area: "Alanganallur", city: "Madurai" },
    { pincode: "625018", area: "Sholavandan", city: "Sholavandan" },
    { pincode: "625019", area: "Usilampatti", city: "Usilampatti" },
    { pincode: "625020", area: "Vadipatti", city: "Vadipatti" },
    { pincode: "625021", area: "T. Kallupatti", city: "Madurai" },
    { pincode: "625022", area: "Peraiyur", city: "Peraiyur" },
    { pincode: "625101", area: "Melur", city: "Melur" },
    { pincode: "625102", area: "Tirumangalam", city: "Tirumangalam" },
    { pincode: "625103", area: "Kalligudi", city: "Madurai" },
    { pincode: "625104", area: "Thiruppalai", city: "Madurai" },
    { pincode: "625201", area: "Thiruppuvanam", city: "Madurai" },
    { pincode: "625205", area: "Uthangudi", city: "Madurai" },
    { pincode: "625402", area: "Samayanallur", city: "Madurai" },
    { pincode: "625601", area: "Kallikudi", city: "Madurai" },
    { pincode: "625602", area: "Elumalai", city: "Madurai" },
  ],

  "Mayiladuthurai": [
    { pincode: "609001", area: "Mayiladuthurai", city: "Mayiladuthurai" },
    { pincode: "609002", area: "Mayiladuthurai Bazaar", city: "Mayiladuthurai" },
    { pincode: "609003", area: "Mayuram", city: "Mayiladuthurai" },
    { pincode: "609101", area: "Sirkazhi", city: "Sirkazhi" },
    { pincode: "609102", area: "Kollidam", city: "Mayiladuthurai" },
    { pincode: "609103", area: "Poompuhar", city: "Mayiladuthurai" },
    { pincode: "609104", area: "Tharangambadi", city: "Tharangambadi" },
    { pincode: "609105", area: "Sembanarkoil", city: "Mayiladuthurai" },
    { pincode: "609106", area: "Kuthalam", city: "Kuthalam" },
    { pincode: "609107", area: "Vaitheeswaran Koil", city: "Mayiladuthurai" },
    { pincode: "609108", area: "Manalmedu", city: "Mayiladuthurai" },
    { pincode: "609109", area: "Thiruvenkadu", city: "Mayiladuthurai" },
    { pincode: "609110", area: "Mallipattinam", city: "Mayiladuthurai" },
  ],

  "Nagapattinam": [
    { pincode: "611001", area: "Nagapattinam", city: "Nagapattinam" },
    { pincode: "611002", area: "Nagapattinam Port", city: "Nagapattinam" },
    { pincode: "611003", area: "Nagore", city: "Nagapattinam" },
    { pincode: "611101", area: "Thiruvarur Road", city: "Nagapattinam" },
    { pincode: "611102", area: "Velankanni", city: "Velankanni" },
    { pincode: "611103", area: "Kilvelur", city: "Kilvelur" },
    { pincode: "611104", area: "Thirukkuvalai", city: "Nagapattinam" },
    { pincode: "611105", area: "Vedaranyam", city: "Vedaranyam" },
    { pincode: "611106", area: "Thalainayar", city: "Nagapattinam" },
    { pincode: "611107", area: "Kodiyakarai", city: "Nagapattinam" },
    { pincode: "611108", area: "Thirumarugal", city: "Nagapattinam" },
    { pincode: "609110", area: "Keelaiyur", city: "Nagapattinam" },
  ],

  "Namakkal": [
    { pincode: "637001", area: "Namakkal", city: "Namakkal" },
    { pincode: "637002", area: "Namakkal Fort", city: "Namakkal" },
    { pincode: "637003", area: "Mohanur", city: "Mohanur" },
    { pincode: "637013", area: "Paramathi Velur", city: "Paramathi Velur" },
    { pincode: "637014", area: "Vennandur", city: "Namakkal" },
    { pincode: "637015", area: "Erumaipatti", city: "Namakkal" },
    { pincode: "637018", area: "Tiruchengode", city: "Tiruchengode" },
    { pincode: "637019", area: "Pallipalayam", city: "Namakkal" },
    { pincode: "637020", area: "Kumarapalayam", city: "Kumarapalayam" },
    { pincode: "637101", area: "Rasipuram", city: "Rasipuram" },
    { pincode: "637102", area: "Sendamangalam", city: "Namakkal" },
    { pincode: "637103", area: "Kolli Hills", city: "Namakkal" },
    { pincode: "637201", area: "Mallasamudram", city: "Namakkal" },
    { pincode: "637202", area: "Elachipalayam", city: "Namakkal" },
    { pincode: "637203", area: "Puduchatram", city: "Namakkal" },
    { pincode: "637204", area: "Velur", city: "Namakkal" },
    { pincode: "637205", area: "Kabilarmalai", city: "Namakkal" },
    { pincode: "637210", area: "Ernapuram", city: "Namakkal" },
  ],

  "Nilgiris": [
    { pincode: "643001", area: "Ooty (Udhagamandalam)", city: "Ooty" },
    { pincode: "643002", area: "Ooty Bazaar", city: "Ooty" },
    { pincode: "643003", area: "Fernhill", city: "Ooty" },
    { pincode: "643004", area: "Lovedale", city: "Ooty" },
    { pincode: "643005", area: "Ketti", city: "Ooty" },
    { pincode: "643006", area: "Wellington", city: "Ooty" },
    { pincode: "643101", area: "Coonoor", city: "Coonoor" },
    { pincode: "643102", area: "Kotagiri", city: "Kotagiri" },
    { pincode: "643103", area: "Gudalur", city: "Gudalur" },
    { pincode: "643104", area: "Pandalur", city: "Pandalur" },
    { pincode: "643105", area: "Devala", city: "Gudalur" },
    { pincode: "643201", area: "Kundah", city: "Ooty" },
    { pincode: "643202", area: "Manjoor", city: "Ooty" },
    { pincode: "643203", area: "Aruvankadu", city: "Coonoor" },
    { pincode: "643204", area: "Aravenu", city: "Ooty" },
    { pincode: "643205", area: "Burliar", city: "Coonoor" },
    { pincode: "643211", area: "Naduvattam", city: "Ooty" },
    { pincode: "643213", area: "Bikketti", city: "Ooty" },
    { pincode: "643214", area: "Emerald", city: "Ooty" },
    { pincode: "643215", area: "Kil Kotagiri", city: "Kotagiri" },
    { pincode: "643217", area: "Cherambadi", city: "Gudalur" },
    { pincode: "643219", area: "Masinagudi", city: "Ooty" },
    { pincode: "643220", area: "Mulli", city: "Ooty" },
    { pincode: "643221", area: "Thengumarahada", city: "Gudalur" },
    { pincode: "643222", area: "Nelliyalam", city: "Gudalur" },
    { pincode: "643223", area: "Sholur", city: "Coonoor" },
    { pincode: "643236", area: "Kodanad", city: "Ooty" },
  ],

  "Perambalur": [
    { pincode: "621212", area: "Perambalur", city: "Perambalur" },
    { pincode: "621213", area: "Perambalur Collectorate", city: "Perambalur" },
    { pincode: "621104", area: "Kunnam", city: "Kunnam" },
    { pincode: "621105", area: "Alathur (Perambalur)", city: "Perambalur" },
    { pincode: "621107", area: "Veppanthattai", city: "Veppanthattai" },
    { pincode: "621108", area: "Chettikulam", city: "Perambalur" },
    { pincode: "621109", area: "Labbaikudikadu", city: "Perambalur" },
    { pincode: "621113", area: "Elambalur", city: "Perambalur" },
    { pincode: "621115", area: "Siruvachur", city: "Perambalur" },
    { pincode: "621116", area: "Ammapalayam", city: "Perambalur" },
    { pincode: "621118", area: "V. Kalathur", city: "Perambalur" },
    { pincode: "621133", area: "Melattur", city: "Perambalur" },
  ],

  "Pudukkottai": [
    { pincode: "622001", area: "Pudukkottai", city: "Pudukkottai" },
    { pincode: "622002", area: "Pudukkottai RS", city: "Pudukkottai" },
    { pincode: "622003", area: "Pudukkottai Fort", city: "Pudukkottai" },
    { pincode: "622101", area: "Aranthangi", city: "Aranthangi" },
    { pincode: "622102", area: "Avudaiyarkoil", city: "Avudaiyarkoil" },
    { pincode: "622103", area: "Karambakudi", city: "Karambakudi" },
    { pincode: "622104", area: "Alangudi", city: "Alangudi" },
    { pincode: "622201", area: "Thirumayam", city: "Thirumayam" },
    { pincode: "622202", area: "Ponnamaravathi", city: "Ponnamaravathi" },
    { pincode: "622203", area: "Gandarvakottai", city: "Gandarvakottai" },
    { pincode: "622204", area: "Illupur", city: "Illupur" },
    { pincode: "622301", area: "Kunnandarkoil", city: "Pudukkottai" },
    { pincode: "622302", area: "Manamelkudi", city: "Pudukkottai" },
    { pincode: "622401", area: "Keeranur", city: "Pudukkottai" },
    { pincode: "622402", area: "Annavasal", city: "Pudukkottai" },
    { pincode: "622502", area: "Viralimalai", city: "Pudukkottai" },
  ],

  "Ramanathapuram": [
    { pincode: "623501", area: "Ramanathapuram", city: "Ramanathapuram" },
    { pincode: "623502", area: "Ramanathapuram Bazaar", city: "Ramanathapuram" },
    { pincode: "623503", area: "Rameswaram", city: "Rameswaram" },
    { pincode: "623504", area: "Dhanushkodi", city: "Rameswaram" },
    { pincode: "623512", area: "Mandapam", city: "Mandapam" },
    { pincode: "623513", area: "Uchipuli", city: "Ramanathapuram" },
    { pincode: "623514", area: "Kadaladi", city: "Ramanathapuram" },
    { pincode: "623515", area: "Paramakudi", city: "Paramakudi" },
    { pincode: "623516", area: "Kamuthi", city: "Kamuthi" },
    { pincode: "623517", area: "Mudukulathur", city: "Mudukulathur" },
    { pincode: "623518", area: "Tiruvadanai", city: "Tiruvadanai" },
    { pincode: "623519", area: "R.S. Mangalam", city: "Ramanathapuram" },
    { pincode: "623520", area: "Nainarkoil", city: "Ramanathapuram" },
    { pincode: "623521", area: "Bogalur", city: "Ramanathapuram" },
    { pincode: "623523", area: "Tondi", city: "Ramanathapuram" },
    { pincode: "623524", area: "Kilakarai", city: "Ramanathapuram" },
    { pincode: "623525", area: "Ervadi", city: "Ramanathapuram" },
  ],

  "Ranipet": [
    { pincode: "632401", area: "Ranipet", city: "Ranipet" },
    { pincode: "632402", area: "Ranipet Bazaar", city: "Ranipet" },
    { pincode: "632403", area: "Arcot", city: "Arcot" },
    { pincode: "632404", area: "Walajah", city: "Walajah" },
    { pincode: "632405", area: "Sholingur", city: "Sholingur" },
    { pincode: "632406", area: "Arakkonam", city: "Arakkonam" },
    { pincode: "632501", area: "Nemili", city: "Nemili" },
    { pincode: "632502", area: "Kalavai", city: "Ranipet" },
    { pincode: "632503", area: "Banavaram", city: "Ranipet" },
    { pincode: "632504", area: "Timiri", city: "Ranipet" },
    { pincode: "632505", area: "Kaveripakkam", city: "Ranipet" },
    { pincode: "631101", area: "Arakkonam RS", city: "Arakkonam" },
  ],

  "Salem": [
    { pincode: "636001", area: "Salem GPO", city: "Salem" },
    { pincode: "636002", area: "Salem Fort", city: "Salem" },
    { pincode: "636003", area: "Salem Bazar", city: "Salem" },
    { pincode: "636004", area: "Salem Junction", city: "Salem" },
    { pincode: "636005", area: "Salem Collectorate", city: "Salem" },
    { pincode: "636006", area: "Suramangalam", city: "Salem" },
    { pincode: "636007", area: "Ammapet (Salem)", city: "Salem" },
    { pincode: "636008", area: "Hasthampatti", city: "Salem" },
    { pincode: "636009", area: "Kondalampatti", city: "Salem" },
    { pincode: "636010", area: "Fairlands", city: "Salem" },
    { pincode: "636011", area: "Alagapuram", city: "Salem" },
    { pincode: "636012", area: "Shevapet", city: "Salem" },
    { pincode: "636013", area: "Junction Road", city: "Salem" },
    { pincode: "636014", area: "Salem Steel Plant", city: "Salem" },
    { pincode: "636015", area: "Attur", city: "Attur" },
    { pincode: "636016", area: "Ayothiyapattinam", city: "Salem" },
    { pincode: "636030", area: "Omalur", city: "Omalur" },
    { pincode: "636101", area: "Mettur", city: "Mettur" },
    { pincode: "636102", area: "Mettur Dam", city: "Mettur" },
    { pincode: "636103", area: "Edappadi", city: "Edappadi" },
    { pincode: "636104", area: "Sankari", city: "Sankari" },
    { pincode: "636105", area: "Yercaud", city: "Yercaud" },
    { pincode: "636106", area: "Gangavalli (Salem)", city: "Salem" },
    { pincode: "636109", area: "Panamarathupatti", city: "Salem" },
    { pincode: "636112", area: "Vazhapadi", city: "Salem" },
    { pincode: "636115", area: "Kolathur (Salem)", city: "Salem" },
    { pincode: "636121", area: "Tharamangalam (Salem)", city: "Salem" },
    { pincode: "636122", area: "Danishpet", city: "Salem" },
    { pincode: "636138", area: "Mecheri", city: "Salem" },
    { pincode: "636141", area: "Nangavalli", city: "Salem" },
    { pincode: "636142", area: "Kadayampatti", city: "Salem" },
  ],

  "Sivaganga": [
    { pincode: "630561", area: "Sivaganga", city: "Sivaganga" },
    { pincode: "630562", area: "Sivaganga Collectorate", city: "Sivaganga" },
    { pincode: "630001", area: "Sivaganga Fort", city: "Sivaganga" },
    { pincode: "630301", area: "Karaikudi", city: "Karaikudi" },
    { pincode: "630302", area: "Devakottai", city: "Devakottai" },
    { pincode: "630303", area: "Ilayangudi", city: "Ilayangudi" },
    { pincode: "630304", area: "Kallal", city: "Sivaganga" },
    { pincode: "630305", area: "Manamadurai", city: "Manamadurai" },
    { pincode: "630306", area: "Tirupattur (Sivaganga)", city: "Sivaganga" },
    { pincode: "630307", area: "Singampunari", city: "Sivaganga" },
    { pincode: "630308", area: "Kalayarkoil", city: "Sivaganga" },
    { pincode: "630309", area: "Thirupuvanam (Sivaganga)", city: "Sivaganga" },
    { pincode: "630310", area: "S. Pudur", city: "Sivaganga" },
    { pincode: "630311", area: "Kottaiyur", city: "Sivaganga" },
    { pincode: "630405", area: "Nattarasankottai", city: "Sivaganga" },
    { pincode: "630411", area: "Chettinad", city: "Karaikudi" },
  ],

  "Tenkasi": [
    { pincode: "627801", area: "Tenkasi", city: "Tenkasi" },
    { pincode: "627802", area: "Tenkasi Collectorate", city: "Tenkasi" },
    { pincode: "627803", area: "Courtallam", city: "Tenkasi" },
    { pincode: "627804", area: "Shencottah", city: "Shencottah" },
    { pincode: "627805", area: "Kadayanallur", city: "Kadayanallur" },
    { pincode: "627806", area: "Sankarankovil", city: "Sankarankovil" },
    { pincode: "627807", area: "Vasudevanallur", city: "Vasudevanallur" },
    { pincode: "627808", area: "Alangulam", city: "Alangulam" },
    { pincode: "627809", area: "Surandai", city: "Surandai" },
    { pincode: "627810", area: "Sivagiri (Tenkasi)", city: "Tenkasi" },
    { pincode: "627811", area: "Puliyangudi", city: "Puliyangudi" },
    { pincode: "627812", area: "Thiruvengadam", city: "Tenkasi" },
    { pincode: "627813", area: "Keelapavoor", city: "Tenkasi" },
    { pincode: "627814", area: "Ayikudi", city: "Tenkasi" },
    { pincode: "627851", area: "Meignanapuram", city: "Tenkasi" },
    { pincode: "627852", area: "Kallidaikurichi", city: "Tenkasi" },
  ],

  "Thanjavur": [
    { pincode: "613001", area: "Thanjavur", city: "Thanjavur" },
    { pincode: "613002", area: "Thanjavur Fort", city: "Thanjavur" },
    { pincode: "613003", area: "Thanjavur Medical College", city: "Thanjavur" },
    { pincode: "613004", area: "Thanjavur Pillayarpatti", city: "Thanjavur" },
    { pincode: "613005", area: "Thanjavur Collectorate", city: "Thanjavur" },
    { pincode: "613006", area: "Thanjavur Palace", city: "Thanjavur" },
    { pincode: "613007", area: "Nanjikottai", city: "Thanjavur" },
    { pincode: "613009", area: "Vallam", city: "Thanjavur" },
    { pincode: "613101", area: "Kumbakonam", city: "Kumbakonam" },
    { pincode: "613102", area: "Kumbakonam RS", city: "Kumbakonam" },
    { pincode: "613103", area: "Swamimalai", city: "Kumbakonam" },
    { pincode: "613104", area: "Thiruvidaimarudur", city: "Kumbakonam" },
    { pincode: "613201", area: "Papanasam", city: "Papanasam" },
    { pincode: "613202", area: "Pattukkottai", city: "Pattukkottai" },
    { pincode: "613203", area: "Peravurani", city: "Peravurani" },
    { pincode: "613204", area: "Orathanadu", city: "Orathanadu" },
    { pincode: "613301", area: "Thiruvaiyaru", city: "Thiruvaiyaru" },
    { pincode: "613303", area: "Budalur", city: "Thanjavur" },
    { pincode: "613401", area: "Thirukkattupalli", city: "Thanjavur" },
    { pincode: "613402", area: "Madukkur", city: "Thanjavur" },
    { pincode: "613501", area: "Sengipatti", city: "Thanjavur" },
    { pincode: "613601", area: "Ayyampettai", city: "Thanjavur" },
    { pincode: "612001", area: "Thiruvarur Road (Thanjavur)", city: "Thanjavur" },
  ],

  "Theni": [
    { pincode: "625531", area: "Theni", city: "Theni" },
    { pincode: "625532", area: "Theni Allinagaram", city: "Theni" },
    { pincode: "625515", area: "Periyakulam", city: "Periyakulam" },
    { pincode: "625516", area: "Bodinayakanur", city: "Bodinayakanur" },
    { pincode: "625517", area: "Cumbum", city: "Cumbum" },
    { pincode: "625518", area: "Andipatti", city: "Andipatti" },
    { pincode: "625519", area: "Uthamapalayam", city: "Uthamapalayam" },
    { pincode: "625520", area: "Chinnamanur", city: "Chinnamanur" },
    { pincode: "625521", area: "Myladumparai", city: "Theni" },
    { pincode: "625522", area: "Gudalur (Theni)", city: "Theni" },
    { pincode: "625523", area: "Veerapandi", city: "Theni" },
    { pincode: "625524", area: "Dombucherry", city: "Theni" },
    { pincode: "625525", area: "Megamalai", city: "Theni" },
    { pincode: "625528", area: "Aundipatti", city: "Theni" },
    { pincode: "625534", area: "Bodi", city: "Theni" },
    { pincode: "625536", area: "Goodalur (Theni)", city: "Theni" },
    { pincode: "625537", area: "Kamayagoundanpatti", city: "Theni" },
  ],

  "Thoothukudi": [
    { pincode: "628001", area: "Thoothukudi GPO", city: "Thoothukudi" },
    { pincode: "628002", area: "Thoothukudi Port", city: "Thoothukudi" },
    { pincode: "628003", area: "Thoothukudi Harbour", city: "Thoothukudi" },
    { pincode: "628004", area: "Thoothukudi Bryant Nagar", city: "Thoothukudi" },
    { pincode: "628005", area: "Thoothukudi Millerpuram", city: "Thoothukudi" },
    { pincode: "628006", area: "Thoothukudi Thermal Nagar", city: "Thoothukudi" },
    { pincode: "628008", area: "SPIC Nagar", city: "Thoothukudi" },
    { pincode: "628101", area: "Tiruchendur", city: "Tiruchendur" },
    { pincode: "628102", area: "Kayalpattinam", city: "Thoothukudi" },
    { pincode: "628103", area: "Kovilpatti", city: "Kovilpatti" },
    { pincode: "628104", area: "Ottapidaram", city: "Thoothukudi" },
    { pincode: "628201", area: "Ettayapuram", city: "Ettayapuram" },
    { pincode: "628202", area: "Srivaikuntam", city: "Srivaikuntam" },
    { pincode: "628203", area: "Sathankulam", city: "Sathankulam" },
    { pincode: "628204", area: "Vilathikulam", city: "Vilathikulam" },
    { pincode: "628205", area: "Udangudi", city: "Thoothukudi" },
    { pincode: "628206", area: "Arumuganeri", city: "Thoothukudi" },
    { pincode: "628207", area: "Kulasekarapattinam", city: "Thoothukudi" },
    { pincode: "628208", area: "Nazareth", city: "Thoothukudi" },
    { pincode: "628211", area: "Kalugumalai", city: "Thoothukudi" },
    { pincode: "628215", area: "Authoor", city: "Thoothukudi" },
    { pincode: "628229", area: "Kayathar", city: "Thoothukudi" },
  ],

  "Tiruchirappalli": [
    { pincode: "620001", area: "Tiruchirappalli GPO", city: "Tiruchirappalli" },
    { pincode: "620002", area: "Tiruchirappalli Fort", city: "Tiruchirappalli" },
    { pincode: "620003", area: "Cantonment", city: "Tiruchirappalli" },
    { pincode: "620004", area: "Palakkarai", city: "Tiruchirappalli" },
    { pincode: "620005", area: "Woraiyur", city: "Tiruchirappalli" },
    { pincode: "620006", area: "Srirangam", city: "Tiruchirappalli" },
    { pincode: "620007", area: "Thillai Nagar", city: "Tiruchirappalli" },
    { pincode: "620008", area: "KK Nagar (Trichy)", city: "Tiruchirappalli" },
    { pincode: "620009", area: "Thiruverumbur", city: "Tiruchirappalli" },
    { pincode: "620010", area: "Golden Rock", city: "Tiruchirappalli" },
    { pincode: "620011", area: "Khajamalai", city: "Tiruchirappalli" },
    { pincode: "620012", area: "Crawford", city: "Tiruchirappalli" },
    { pincode: "620013", area: "BIT Campus", city: "Tiruchirappalli" },
    { pincode: "620014", area: "NIT Trichy", city: "Tiruchirappalli" },
    { pincode: "620015", area: "Anna Nagar (Trichy)", city: "Tiruchirappalli" },
    { pincode: "620016", area: "Kattur", city: "Tiruchirappalli" },
    { pincode: "620017", area: "Tennur", city: "Tiruchirappalli" },
    { pincode: "620018", area: "Vayalur Road", city: "Tiruchirappalli" },
    { pincode: "620019", area: "Ariyamangalam", city: "Tiruchirappalli" },
    { pincode: "620020", area: "Manchanallur", city: "Tiruchirappalli" },
    { pincode: "620021", area: "Thuraiyur", city: "Thuraiyur" },
    { pincode: "620101", area: "Lalgudi", city: "Lalgudi" },
    { pincode: "620102", area: "Musiri", city: "Musiri" },
    { pincode: "621201", area: "Manachanallur", city: "Tiruchirappalli" },
    { pincode: "621202", area: "Manapparai", city: "Manapparai" },
    { pincode: "621206", area: "Marungapuri", city: "Tiruchirappalli" },
    { pincode: "621207", area: "Uppiliyapuram", city: "Tiruchirappalli" },
    { pincode: "621211", area: "Pullambadi", city: "Tiruchirappalli" },
    { pincode: "621301", area: "Srirangam Temple", city: "Tiruchirappalli" },
  ],

  "Tirunelveli": [
    { pincode: "627001", area: "Tirunelveli GPO", city: "Tirunelveli" },
    { pincode: "627002", area: "Tirunelveli Junction", city: "Tirunelveli" },
    { pincode: "627003", area: "Tirunelveli Fort", city: "Tirunelveli" },
    { pincode: "627004", area: "Palayamkottai", city: "Tirunelveli" },
    { pincode: "627005", area: "Melapalayam", city: "Tirunelveli" },
    { pincode: "627006", area: "Tirunelveli Town", city: "Tirunelveli" },
    { pincode: "627007", area: "Pettai", city: "Tirunelveli" },
    { pincode: "627008", area: "Maharaja Nagar", city: "Tirunelveli" },
    { pincode: "627009", area: "Vannarpettai", city: "Tirunelveli" },
    { pincode: "627010", area: "Murugankurichi", city: "Tirunelveli" },
    { pincode: "627011", area: "Tirunelveli Medical College", city: "Tirunelveli" },
    { pincode: "627101", area: "Ambasamudram", city: "Ambasamudram" },
    { pincode: "627102", area: "Nanguneri", city: "Nanguneri" },
    { pincode: "627103", area: "Radhapuram", city: "Radhapuram" },
    { pincode: "627104", area: "Cheranmahadevi", city: "Tirunelveli" },
    { pincode: "627105", area: "Kalakkad", city: "Kalakkad" },
    { pincode: "627106", area: "Manur", city: "Tirunelveli" },
    { pincode: "627107", area: "Thisayanvilai", city: "Tirunelveli" },
    { pincode: "627108", area: "Vallioor", city: "Tirunelveli" },
    { pincode: "627111", area: "Papanasam (Tirunelveli)", city: "Tirunelveli" },
    { pincode: "627112", area: "Keezhapavoor", city: "Tirunelveli" },
    { pincode: "627151", area: "Pottalpudur", city: "Tirunelveli" },
    { pincode: "627152", area: "Kadayam", city: "Tirunelveli" },
    { pincode: "627201", area: "Tenkasi Road", city: "Tirunelveli" },
  ],

  "Tirupattur": [
    { pincode: "635601", area: "Tirupattur", city: "Tirupattur" },
    { pincode: "635602", area: "Tirupattur Bazaar", city: "Tirupattur" },
    { pincode: "635651", area: "Ambur", city: "Ambur" },
    { pincode: "635652", area: "Natrampalli", city: "Natrampalli" },
    { pincode: "635653", area: "Vaniyambadi", city: "Vaniyambadi" },
    { pincode: "635654", area: "Jolarpet", city: "Jolarpet" },
    { pincode: "635701", area: "Kandhili", city: "Tirupattur" },
    { pincode: "635702", area: "Alangayam", city: "Tirupattur" },
    { pincode: "635703", area: "Madhanur", city: "Tirupattur" },
    { pincode: "635710", area: "Peranambut", city: "Tirupattur" },
    { pincode: "635751", area: "Naidupet (Tirupattur)", city: "Tirupattur" },
    { pincode: "635752", area: "Thatchur", city: "Tirupattur" },
    { pincode: "635754", area: "Velakkalnatham", city: "Tirupattur" },
    { pincode: "635801", area: "Ammundi", city: "Tirupattur" },
    { pincode: "635810", area: "Kavalur", city: "Tirupattur" },
  ],

  "Tiruppur": [
    { pincode: "641601", area: "Tiruppur", city: "Tiruppur" },
    { pincode: "641602", area: "Tiruppur South", city: "Tiruppur" },
    { pincode: "641603", area: "Tiruppur East", city: "Tiruppur" },
    { pincode: "641604", area: "Tiruppur North", city: "Tiruppur" },
    { pincode: "641605", area: "Nallur", city: "Tiruppur" },
    { pincode: "641606", area: "Mangalam", city: "Tiruppur" },
    { pincode: "641607", area: "SIPCOT Perundurai", city: "Tiruppur" },
    { pincode: "641608", area: "Avinashi", city: "Avinashi" },
    { pincode: "641651", area: "Palladam", city: "Palladam" },
    { pincode: "641652", area: "Udumalpet", city: "Udumalpet" },
    { pincode: "641658", area: "Dharapuram", city: "Dharapuram" },
    { pincode: "641659", area: "Kangeyam", city: "Kangeyam" },
    { pincode: "641660", area: "Kundadam", city: "Tiruppur" },
    { pincode: "641661", area: "Vellakoil", city: "Vellakoil" },
    { pincode: "641662", area: "Mulanur", city: "Tiruppur" },
    { pincode: "641663", area: "Madathukulam", city: "Tiruppur" },
    { pincode: "641664", area: "Gudimangalam", city: "Tiruppur" },
    { pincode: "641665", area: "Pongalur", city: "Tiruppur" },
    { pincode: "641666", area: "Uthukuli", city: "Tiruppur" },
    { pincode: "641667", area: "Muthur", city: "Tiruppur" },
    { pincode: "641668", area: "Tiruppur Collectorate", city: "Tiruppur" },
    { pincode: "641669", area: "Perumanallur", city: "Tiruppur" },
    { pincode: "641670", area: "Kaniyur", city: "Tiruppur" },
  ],

  "Tiruvallur": [
    { pincode: "602001", area: "Tiruvallur", city: "Tiruvallur" },
    { pincode: "602002", area: "Tiruvallur Collectorate", city: "Tiruvallur" },
    { pincode: "602003", area: "Tiruttani", city: "Tiruttani" },
    { pincode: "602024", area: "Gummidipoondi", city: "Gummidipoondi" },
    { pincode: "602025", area: "Ponneri", city: "Ponneri" },
    { pincode: "602026", area: "Uthukkottai", city: "Uthukkottai" },
    { pincode: "602101", area: "Ambattur Industrial Estate", city: "Chennai" },
    { pincode: "602103", area: "Avadi Camp", city: "Avadi" },
    { pincode: "602104", area: "Thiruninravur", city: "Tiruvallur" },
    { pincode: "602105", area: "Pattabiram", city: "Tiruvallur" },
    { pincode: "602107", area: "Kadambattur", city: "Tiruvallur" },
    { pincode: "602109", area: "Tiruverkadu", city: "Tiruvallur" },
    { pincode: "602110", area: "Ennore Port", city: "Tiruvallur" },
    { pincode: "601101", area: "Tiruvottiyur", city: "Tiruvallur" },
    { pincode: "601201", area: "RK Pet", city: "Tiruvallur" },
    { pincode: "601202", area: "Nemilichery", city: "Tiruvallur" },
    { pincode: "601203", area: "Uthiramerur", city: "Tiruvallur" },
    { pincode: "601204", area: "Pallipat", city: "Tiruvallur" },
    { pincode: "631301", area: "Perambur (Tiruvallur)", city: "Tiruvallur" },
  ],

  "Tiruvannamalai": [
    { pincode: "606601", area: "Tiruvannamalai", city: "Tiruvannamalai" },
    { pincode: "606602", area: "Tiruvannamalai Temple", city: "Tiruvannamalai" },
    { pincode: "606603", area: "Tiruvannamalai Collectorate", city: "Tiruvannamalai" },
    { pincode: "606604", area: "Arani", city: "Arani" },
    { pincode: "606611", area: "Polur", city: "Polur" },
    { pincode: "606701", area: "Chengam", city: "Chengam" },
    { pincode: "606702", area: "Cheyyar", city: "Cheyyar" },
    { pincode: "606703", area: "Vandavasi", city: "Vandavasi" },
    { pincode: "606704", area: "Chetpet (TVmalai)", city: "Tiruvannamalai" },
    { pincode: "606705", area: "Jawadhu Hills", city: "Tiruvannamalai" },
    { pincode: "606706", area: "Kalasapakkam", city: "Tiruvannamalai" },
    { pincode: "606707", area: "Kilpennathur", city: "Tiruvannamalai" },
    { pincode: "606708", area: "Thandrampattu", city: "Tiruvannamalai" },
    { pincode: "606709", area: "West Arani", city: "Tiruvannamalai" },
    { pincode: "606710", area: "Vettavalam", city: "Tiruvannamalai" },
    { pincode: "606751", area: "Desur", city: "Tiruvannamalai" },
    { pincode: "606752", area: "Anakkavur", city: "Tiruvannamalai" },
    { pincode: "606753", area: "Pernampattu", city: "Tiruvannamalai" },
    { pincode: "606801", area: "Sat Kunda", city: "Tiruvannamalai" },
    { pincode: "606901", area: "Sankarapuram (TVmalai)", city: "Tiruvannamalai" },
    { pincode: "604501", area: "Arni (TVmalai)", city: "Tiruvannamalai" },
  ],

  "Tiruvarur": [
    { pincode: "610001", area: "Tiruvarur", city: "Tiruvarur" },
    { pincode: "610002", area: "Tiruvarur Temple", city: "Tiruvarur" },
    { pincode: "610003", area: "Tiruvarur Collectorate", city: "Tiruvarur" },
    { pincode: "610101", area: "Mannargudi", city: "Mannargudi" },
    { pincode: "610102", area: "Thiruthuraipoondi", city: "Thiruthuraipoondi" },
    { pincode: "610103", area: "Needamangalam", city: "Needamangalam" },
    { pincode: "610104", area: "Nannilam", city: "Nannilam" },
    { pincode: "610105", area: "Kodavasal", city: "Kodavasal" },
    { pincode: "610106", area: "Valangaiman", city: "Valangaiman" },
    { pincode: "610107", area: "Koothanallur", city: "Koothanallur" },
    { pincode: "610108", area: "Muthupet", city: "Muthupet" },
    { pincode: "610109", area: "Kottur", city: "Tiruvarur" },
    { pincode: "610201", area: "Tiruvarur RS", city: "Tiruvarur" },
    { pincode: "610202", area: "Tirumakkottai", city: "Tiruvarur" },
    { pincode: "610203", area: "Sankaraguptam", city: "Tiruvarur" },
    { pincode: "610204", area: "Koradacheri", city: "Tiruvarur" },
    { pincode: "614903", area: "Sethubavachatram", city: "Tiruvarur" },
  ],

  "Vellore": [
    { pincode: "632001", area: "Vellore GPO", city: "Vellore" },
    { pincode: "632002", area: "Vellore Fort", city: "Vellore" },
    { pincode: "632004", area: "Vellore Bazaar", city: "Vellore" },
    { pincode: "632006", area: "Vellore Collectorate", city: "Vellore" },
    { pincode: "632007", area: "Katpadi", city: "Vellore" },
    { pincode: "632008", area: "Sathuvachari", city: "Vellore" },
    { pincode: "632009", area: "Kagithapattarai", city: "Vellore" },
    { pincode: "632010", area: "CMC Vellore", city: "Vellore" },
    { pincode: "632011", area: "VIT University", city: "Vellore" },
    { pincode: "632013", area: "Thorapadi", city: "Vellore" },
    { pincode: "632014", area: "Saidapet (Vellore)", city: "Vellore" },
    { pincode: "632055", area: "Gudiyatham", city: "Gudiyatham" },
    { pincode: "632057", area: "Pernambut", city: "Vellore" },
    { pincode: "632101", area: "Anaicut", city: "Vellore" },
    { pincode: "632102", area: "K.V. Kuppam", city: "Vellore" },
    { pincode: "632103", area: "Kannamangalam", city: "Vellore" },
    { pincode: "632104", area: "Pallikonda", city: "Vellore" },
    { pincode: "632105", area: "Odugathur", city: "Vellore" },
    { pincode: "632106", area: "Pennathur", city: "Vellore" },
    { pincode: "632107", area: "Virinjipuram", city: "Vellore" },
    { pincode: "632114", area: "Melvisharam", city: "Vellore" },
    { pincode: "632201", area: "Ambur (Vellore)", city: "Vellore" },
    { pincode: "632202", area: "Vaniyambadi (Vellore)", city: "Vellore" },
    { pincode: "632301", area: "Tirupattur (Vellore)", city: "Vellore" },
    { pincode: "632311", area: "Alangayam (Vellore)", city: "Vellore" },
    { pincode: "635809", area: "Natrampalli (Vellore)", city: "Vellore" },
  ],

  "Viluppuram": [
    { pincode: "605601", area: "Viluppuram", city: "Viluppuram" },
    { pincode: "605602", area: "Viluppuram Collectorate", city: "Viluppuram" },
    { pincode: "605401", area: "Tindivanam", city: "Tindivanam" },
    { pincode: "605402", area: "Gingee", city: "Gingee" },
    { pincode: "605501", area: "Kallakurichi (old)", city: "Viluppuram" },
    { pincode: "605502", area: "Sankarapuram (VP)", city: "Viluppuram" },
    { pincode: "605602", area: "Mundiyampakkam", city: "Viluppuram" },
    { pincode: "605701", area: "Vanur", city: "Vanur" },
    { pincode: "605702", area: "Marakkanam", city: "Marakkanam" },
    { pincode: "605751", area: "Vikravandi", city: "Viluppuram" },
    { pincode: "605752", area: "Koliyanur", city: "Viluppuram" },
    { pincode: "605801", area: "Thiruvennainallur", city: "Viluppuram" },
    { pincode: "605802", area: "Ulundurpet (VP)", city: "Viluppuram" },
    { pincode: "606001", area: "Villianur", city: "Viluppuram" },
    { pincode: "606101", area: "Auroville", city: "Viluppuram" },
    { pincode: "606102", area: "Kandachipuram", city: "Viluppuram" },
    { pincode: "606103", area: "Mailam", city: "Viluppuram" },
    { pincode: "606104", area: "Kanjanur", city: "Viluppuram" },
    { pincode: "604001", area: "Pondicherry Road", city: "Viluppuram" },
  ],

  "Virudhunagar": [
    { pincode: "626001", area: "Virudhunagar", city: "Virudhunagar" },
    { pincode: "626002", area: "Virudhunagar Bazaar", city: "Virudhunagar" },
    { pincode: "626003", area: "Virudhunagar RS", city: "Virudhunagar" },
    { pincode: "626101", area: "Sivakasi", city: "Sivakasi" },
    { pincode: "626102", area: "Sivakasi Industrial", city: "Sivakasi" },
    { pincode: "626103", area: "Srivilliputhur", city: "Srivilliputhur" },
    { pincode: "626104", area: "Rajapalayam", city: "Rajapalayam" },
    { pincode: "626105", area: "Aruppukkottai", city: "Aruppukkottai" },
    { pincode: "626106", area: "Sattur", city: "Sattur" },
    { pincode: "626110", area: "Vembakottai", city: "Virudhunagar" },
    { pincode: "626111", area: "Watrap", city: "Virudhunagar" },
    { pincode: "626112", area: "Thiruchuli", city: "Virudhunagar" },
    { pincode: "626113", area: "Kariapatti", city: "Virudhunagar" },
    { pincode: "626114", area: "Narikudi", city: "Virudhunagar" },
    { pincode: "626115", area: "Sundarapandiapuram", city: "Virudhunagar" },
    { pincode: "626117", area: "Mamsapuram", city: "Virudhunagar" },
    { pincode: "626123", area: "Tiruchuli", city: "Virudhunagar" },
    { pincode: "626131", area: "Chathirapatti", city: "Virudhunagar" },
    { pincode: "626132", area: "Seithur", city: "Virudhunagar" },
    { pincode: "626140", area: "Sankarankoil (VN)", city: "Virudhunagar" },
    { pincode: "626141", area: "Paraipatti", city: "Virudhunagar" },
    { pincode: "626189", area: "Kalligaranpatti", city: "Virudhunagar" },
  ],
};
