module.exports = [
  { "code": "AN", "name": "Andaman and Nicobar Islands", "type": "UT" },
  { "code": "AP", "name": "Andhra Pradesh", "type": "State" },
  { "code": "AR", "name": "Arunachal Pradesh", "type": "State" },
  { "code": "AS", "name": "Assam", "type": "State" },
  { "code": "BR", "name": "Bihar", "type": "State" },
  { "code": "CH", "name": "Chandigarh", "type": "UT" },
  { "code": "CT", "name": "Chhattisgarh", "type": "State" },
  { "code": "DN", "name": "Dadra and Nagar Haveli and Daman and Diu", "type": "UT" },
  { "code": "DL", "name": "Delhi", "type": "UT" },
  { "code": "GA", "name": "Goa", "type": "State" },
  { "code": "GJ", "name": "Gujarat", "type": "State" },
  { "code": "HR", "name": "Haryana", "type": "State" },
  { "code": "HP", "name": "Himachal Pradesh", "type": "State" },
  { "code": "JH", "name": "Jharkhand", "type": "State" },
  { "code": "JK", "name": "Jammu and Kashmir", "type": "UT" },
  { "code": "KA", "name": "Karnataka", "type": "State" },
  { "code": "KL", "name": "Kerala", "type": "State" },
  { "code": "LA", "name": "Ladakh", "type": "UT" },
  { "code": "LD", "name": "Lakshadweep", "type": "UT" },
  { "code": "MH", "name": "Maharashtra", "type": "State" },
  { "code": "MN", "name": "Manipur", "type": "State" },
  { "code": "ML", "name": "Meghalaya", "type": "State" },
  { "code": "MZ", "name": "Mizoram", "type": "State" },
  { "code": "NL", "name": "Nagaland", "type": "State" },
  { "code": "OR", "name": "Odisha", "type": "State" },
  { "code": "PB", "name": "Punjab", "type": "State" },
  { "code": "PY", "name": "Puducherry", "type": "UT" },
  { "code": "RJ", "name": "Rajasthan", "type": "State" },
  { "code": "SK", "name": "Sikkim", "type": "State" },
  {
    "code": "TN", "name": "Tamil Nadu", "type": "State",
    "districts": {
      "Ariyalur": [],
      "Chengalpattu": [],
      "Chennai": [],
      "Coimbatore": [
        { "pincode": "641001", "area": "Town Hall", "city": "Coimbatore" },
        { "pincode": "641002", "area": "RS Puram", "city": "Coimbatore" },
        { "pincode": "641003", "area": "Lawley Road", "city": "Coimbatore" },
        { "pincode": "641004", "area": "Peelamedu", "city": "Coimbatore" },
        { "pincode": "641005", "area": "Singanallur", "city": "Coimbatore" },
        { "pincode": "641006", "area": "Ganapathy", "city": "Coimbatore" },
        { "pincode": "641007", "area": "Veerakeralam", "city": "Coimbatore" },
        { "pincode": "641008", "area": "Kuniamuthur", "city": "Coimbatore" },
        { "pincode": "641009", "area": "Ramnagar", "city": "Coimbatore" },
        { "pincode": "641010", "area": "Perur", "city": "Coimbatore" },
        { "pincode": "641011", "area": "Saibaba Colony", "city": "Coimbatore" },
        { "pincode": "641012", "area": "Gandhipuram", "city": "Coimbatore" },
        { "pincode": "641013", "area": "GCT Campus", "city": "Coimbatore" },
        { "pincode": "641014", "area": "Civil Aerodrome", "city": "Coimbatore" },
        { "pincode": "641015", "area": "Uppilipalayam", "city": "Coimbatore" },
        { "pincode": "641016", "area": "Ondipudur", "city": "Coimbatore" },
        { "pincode": "641017", "area": "Vadamadurai", "city": "Coimbatore" },
        { "pincode": "641018", "area": "Coimbatore Central", "city": "Coimbatore" },
        { "pincode": "641019", "area": "Press Colony", "city": "Coimbatore" },
        { "pincode": "641020", "area": "Periyanaickenpalayam", "city": "Coimbatore" },
        { "pincode": "641021", "area": "Industrial Estate", "city": "Coimbatore" },
        { "pincode": "641022", "area": "NGGO Colony", "city": "Coimbatore" },
        { "pincode": "641023", "area": "Podanur", "city": "Coimbatore" },
        { "pincode": "641024", "area": "Sundarapuram", "city": "Coimbatore" },
        { "pincode": "641025", "area": "Eachanari", "city": "Coimbatore" },
        { "pincode": "641026", "area": "Madukkarai", "city": "Coimbatore" },
        { "pincode": "641027", "area": "Rathinapuri", "city": "Coimbatore" },
        { "pincode": "641028", "area": "Sowripalayam", "city": "Coimbatore" },
        { "pincode": "641029", "area": "Gnanambika Mills", "city": "Coimbatore" },
        { "pincode": "641030", "area": "Kavundampalayam", "city": "Coimbatore" },
        { "pincode": "641031", "area": "Velandipalayam", "city": "Coimbatore" },
        { "pincode": "641032", "area": "Othakalmandapam", "city": "Coimbatore" },
        { "pincode": "641033", "area": "Nehru Nagar", "city": "Coimbatore" },
        { "pincode": "641034", "area": "Thudiyalur", "city": "Coimbatore" },
        { "pincode": "641035", "area": "Saravanampatti", "city": "Coimbatore" },
        { "pincode": "641036", "area": "Narasimhanaickenpalayam", "city": "Coimbatore" },
        { "pincode": "641037", "area": "KK Pudur", "city": "Coimbatore" },
        { "pincode": "641038", "area": "Kuppakonam Pudur", "city": "Coimbatore" },
        { "pincode": "641039", "area": "Telungupalayam", "city": "Coimbatore" },
        { "pincode": "641040", "area": "Subramaniyapuram", "city": "Coimbatore" },
        { "pincode": "641041", "area": "Vadavalli", "city": "Coimbatore" },
        { "pincode": "641042", "area": "Kurichi", "city": "Coimbatore" },
        { "pincode": "641043", "area": "Sanganur", "city": "Coimbatore" },
        { "pincode": "641044", "area": "Siddhapudur", "city": "Coimbatore" },
        { "pincode": "641045", "area": "Ramanathapuram", "city": "Coimbatore" },
        { "pincode": "641046", "area": "Bharathiar University", "city": "Coimbatore" },
        { "pincode": "641047", "area": "Jothipuram", "city": "Coimbatore" },
        { "pincode": "641048", "area": "Kalapatti", "city": "Coimbatore" },
        { "pincode": "641049", "area": "Vilankurichi", "city": "Coimbatore" },
        { "pincode": "641050", "area": "Pappanaickenpalayam", "city": "Coimbatore" },
        { "pincode": "641062", "area": "Karamadai", "city": "Mettupalayam" },
        { "pincode": "641101", "area": "Mettupalayam", "city": "Mettupalayam" },
        { "pincode": "641105", "area": "Sirumugai", "city": "Mettupalayam" },
        { "pincode": "642001", "area": "Pollachi", "city": "Pollachi" },
        { "pincode": "642002", "area": "Pollachi Bazaar", "city": "Pollachi" },
        { "pincode": "642003", "area": "Mahalingapuram", "city": "Pollachi" },
        { "pincode": "642007", "area": "Kinathukadavu", "city": "Pollachi" },
        { "pincode": "642010", "area": "Anaimalai", "city": "Pollachi" },
        { "pincode": "642103", "area": "Valparai", "city": "Valparai" },
        { "pincode": "641653", "area": "Sulur", "city": "Sulur" },
        { "pincode": "641654", "area": "Irugur", "city": "Sulur" },
        { "pincode": "641655", "area": "Karumathampatti", "city": "Coimbatore" },
        { "pincode": "641656", "area": "Annur", "city": "Coimbatore" },
        { "pincode": "641657", "area": "Kovilpalayam", "city": "Coimbatore" }
      ],
      "Cuddalore": [],
      "Dharmapuri": [],
      "Dindigul": [],
      "Erode": [],
      "Kallakurichi": [],
      "Kancheepuram": [],
      "Karur": [],
      "Krishnagiri": [],
      "Madurai": [],
      "Mayiladuthurai": [],
      "Nagapattinam": [],
      "Namakkal": [],
      "Nilgiris": [],
      "Perambalur": [],
      "Pudukkottai": [],
      "Ramanathapuram": [],
      "Ranipet": [],
      "Salem": [],
      "Sivaganga": [],
      "Tenkasi": [],
      "Thanjavur": [],
      "Theni": [],
      "Thoothukudi": [],
      "Tiruchirappalli": [],
      "Tirunelveli": [],
      "Tirupattur": [],
      "Tiruppur": [],
      "Tiruvallur": [],
      "Tiruvannamalai": [],
      "Tiruvarur": [],
      "Vellore": [],
      "Viluppuram": [],
      "Virudhunagar": []
    }
  },
  { "code": "TG", "name": "Telangana", "type": "State" },
  { "code": "TR", "name": "Tripura", "type": "State" },
  { "code": "UP", "name": "Uttar Pradesh", "type": "State" },
  { "code": "UT", "name": "Uttarakhand", "type": "State" },
  { "code": "WB", "name": "West Bengal", "type": "State" }
];
